- docs/githubteacher.md
This Pull Request adds a bio for @githubteacher as requested in #9.
@githubstudent I would :heart: if you had :watch: to put some :eyes: and :thought_balloon:s on this.
> Add a bio for @githubteacher

- docs/sandhya1212015.md
This pull request adds a bio for @sandhya1212015 as requested in #31.
@githubteacher  Please review my request
> Add a bio for @sandhya

- docs/chowkong.md
This Pull Request adds a bio for @chowkong as requested in #12.
@githubstudent  do you have time to put some eyes and thoughts on this.
> Add a bio for @chowkong

- docs/astudt.md
This Pull Request adds a bio for @astudt as requested in #16. 
@githubstudent
> Add a bio for @astudt

- docs/marinak222.md
This pull request adds a bio for @marinak222 as requested in #33 
@githubteacher please review my request
> Add a bio for @marinak222

- docs/kotharip.md
This pull request adds a bio for @githubstudent as requested in #24 
@githubstudent I would :heart: if you had :watch: to put some :eyes: and :thought_balloon:s on this.
> Add a bio for kotharip

- docs/intuitgeorgen.md
This pull request adds a bio for @intuitgeorgen as requested in #18 
@astudt 
@mlawrence1-intuit  
@doug-beach please add something sarcastic here
> Add a bio for @IntuitGeorgen

- docs/gsaggar.md
This pull request adds a bio for @gsaggar as requested in #17.
@gsaggar I would :heart: if you had :watch: to put some :eyes: and :thought_balloon:s on this.
> Add a bio for @gsaggar

- docs/sporcina.md
This pull request adds a bio for @sporcina as requested in #10.
@TrevorTheIntuitCoder I would :100:% like you to review this please :)
> Add a bio for @sporcina

- docs/sagarbarbhaya.md
This Pull request adds a bio for @sagarbarbhaya as requested in #20. 
@githubstudent I would :heart: if you had :watch: to put some :eyes: and :thought_balloon:s on this.
> Add a bio for @sagarbarbhaya

- docs/sumanmalla.md
This pull request adds a bio for @sumanmalla as requested in issue #15.
@githubteacher - i would like you to review the changes.
> Add a bio for @sumanmalla

- docs/abhijeet11.md
This Pull request add a bio for @abhijeet11 as requested in #38.
@githubstudent I would like you to look into the issue.
> Add Bio for @abhijeet11

- docs/ciychodianda.md
This Pull Request adds a bio for @ciychodianda as requested in #28 
@githubstudent Please share your thoughts
> Add bio for @ciychodianda

- docs/nehasikri.md
This pull request adds a bio for @nehasikri as requested in #27.
@githubteacher: I would appreciate if you could have a look at it and provide feedback :)
> Add a bio for @nehasikri

- docs/snene.md
This pull request adds a bio for @snene as requested in #32 
@githubteacher - Please review mu changes and provide feedback!
> Add bio for @snene

- docs/7mary4.md
The Pull Request adds a bio for @7mary4 as requested in #13. 
@sagarbarbhaya, notice I used a definition list :smile:
> Add bio for 7mary4

- docs/mlawrence1-intuit.md
> Add bio for @mlawrence1-intuit

- docs/geckel.md
This Pull Request adds a bio for @geckel as requested in issue #23.
@githubteacher   I'd :heart: you to put some :eyes: on these changes.
> Adds a bio for @geckel

- docs/TrevorTheIntuitCoder.md
This Pull Request adds the bio for @TrevorTheIntuitCoder as requested in #5 
@nehasikri @horacechan @sporcina Did I spell my name right? :ok: :meat_on_bone: :8ball: :earth_asia: :dancers: :hamster:
> Merging tcook-bio branch back into master

- docs/HeyItsManny.md
This pull request adds a bio for @HeyItsManny as requested in #22.
> Add a bio for @HeyItsManny

- docs/horacechan.md
This Pull request adds a bio for @horacechan as request in #21.
@TrevorTheIntuitCoder What do you think? :star: or :hankey:
> Add a bio for @horacechan

- docs/dan-steinberg-intuit.md
This Pull Request adds a bio for @Dan-Steinberg-Intuit as requested in #34 .
@githubstudent, please review and comment on this as needed.  Thanks!
> Add bio for @Dan-Steinberg-Intuit

- docs/aduppala1986.md
This Pull Request adds a bio for @aduppala1986 as requested in #14 
@githubteacher I would :heart: if you had :watch: to put some :eyes: and :thought_balloon:s on this.
> Add a bio for @aduppala1986

- docs/ruchikadhingra.md
> Add the md file to this branch

- docs/ciychodianda.md
This Pulls Request adds a favorite vacation spot for @ciychodianda
> Add favorite vacation spot for @ciychodianda

- docs/7mary4.md
This adds a favorite destination
> Added favorite destination

- docs/gsaggar.md
This pull request adds a favorite vacation spot for @gsaggar
> Add a favorite vacation spot for @gsaggar
